blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/tttapa/Control-Surface/discussions
    about: Please use the “Discussions” section for questions that are not bug reports or feature requests.
